### ISSUE TITLE
Swift codes are not suitable for 1.2

### ISSUE THREAD

**Issue by loplopLover** [Vazzi/VJAutocomplete#1]
Hello,

Your swift codes are not suitable for 1.2. Do you make any plan for updating the codes?

Thanks,

Haydar

**Comment by Vazzi** [comment]
Hi, 

I am gonna look at it this or next week. I dont have much time these days:). Thank you for asking. I'll try to do it as soon as posible.

JV

**Comment by loplopLover** [comment]
Hi again,

Thank you for quick response. I look forward to your update :)

Good day,

Haydar

**Comment by Vazzi** [comment]
It should be ready for latest Swift. Thanks again for reminding me:) Use tag 1.3 or newest master.
