### ISSUE TITLE
What should I do for two UITextField?

### ISSUE THREAD

**Issue by loplopLover** [Vazzi/VJAutocomplete#2]
Hello,

I have two UITextField in a viewController. What should I do for two UITextField? It just worked for one of them.

Source Codes: https://gist.github.com/haydarKarkin/c56d541db2b86e6d9774

Can you give me any advice for this situation?

Thanks,

Haydar

**Comment by Vazzi** [comment]
I tried to write my own code with two textFields and it works. Then I looked at your code and try it and it also works. I do not see any problem. So, it looks like the VJAutocomplete is ok. But there may be problem somewhere else. 

Check storyboard if it is correctly set and try to debug your code. Add some breakpoints to shouldChangeCharacters(...) and showAutocomplete(...) functions in VJAutocomplete if they are even called.

I do not know how else I can help. If you find the problem write it here. I would like to hear what it is. Maybe there is a little bug that makes it not working with some of your code. If it is the case I will be happy to fix it. :)

**Comment by loplopLover** [comment]
Could you see that second texfield works with autocomplete? Because, first one works for me, however, second one doesn't. :(

**Comment by Vazzi** [comment]
Yes, both of them work. You can try to write it as a new application with only those too textFields. Then try to add some of your code to analyze where is the bug.

**Comment by loplopLover** [comment]
Hello again, I tried some codes to analyze where is bug, I could not find it. Can you share your codes with me for example?

**Comment by Vazzi** [comment]
Sure, look at  TwoTextFields branch (https://github.com/Vazzi/VJAutocomplete/tree/TwoTextFields). In Swift demo folder is project where are two UITextFields. Hope it helps. :)
